packages:
  - packages/*
  - apps/*

blockExoticSubdeps: true

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 43200
