packages:
  - packages/*
  - apps/*

blockExoticSubdeps: true

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1

minimumReleaseAge: 10080

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 43200
engineStrict: true
allowBuilds:
  '@swc/core': true
  esbuild: true
