packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild

blockExoticSubdeps: true
minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200

catalog:
  react: ^18.2.0
  react-dom: ^18.2.0